// <auto-generated />
using System;
using Event_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Event_Management_System.Migrations
{
    [DbContext(typeof(MasDbContext))]
    [Migration("20251229153404_CreatePopularEventsView")]
    partial class CreatePopularEventsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DiscussionComment", b =>
                {
                    b.Property<int>("DiscussionCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscussionCommentId");

                    b.HasIndex("TargetEventId");

                    b.HasIndex("UserId");

                    b.ToTable("DiscussionComments");
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EventEventCategory", b =>
                {
                    b.Property<int>("CategoriesEventCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesEventCategoryId", "EventsEventId");

                    b.HasIndex("EventsEventId");

                    b.ToTable("EventCategoryLink", (string)null);
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSpots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.EventCategory", b =>
                {
                    b.Property<int>("EventCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventCategoryId");

                    b.ToTable("EventCategories");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ViewDate")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PaymentDetail", b =>
                {
                    b.Property<int>("PaymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentDetailId");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PromotedRequest", b =>
                {
                    b.Property<int>("PromotedRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PromotionEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("PromotedRequestId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("PromotedRequests");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("PaymentDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromotedRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentDetailId");

                    b.HasIndex("PromotedRequestId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserTypes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VenueId");

                    b.HasIndex("LocationId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("UserFollow", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserFollow");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Organizer", b =>
                {
                    b.HasBaseType("Event_Management_System.Models.Base.User");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Earning")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsMonetized")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.RegularUser", b =>
                {
                    b.HasBaseType("Event_Management_System.Models.Base.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Regular");
                });

            modelBuilder.Entity("DiscussionComment", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.Event", "TargetEvent")
                        .WithMany("Comments")
                        .HasForeignKey("TargetEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("TargetEvent");
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.Event", "Event")
                        .WithMany("Enrollments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventEventCategory", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.EventCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesEventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Event", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Message", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.User", "Receiver")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PaymentDetail", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.User", "OwnerUser")
                        .WithOne("PaymentDetail")
                        .HasForeignKey("Event_Management_System.Models.Base.PaymentDetail", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PromotedRequest", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.Event", "TargetEvent")
                        .WithMany("PromotedRequests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.Organizer", "Organizer")
                        .WithMany("PromotedRequests")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("TargetEvent");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Transaction", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.PaymentDetail", "PaymentDetail")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.PromotedRequest", "PromotedRequest")
                        .WithMany("Transactions")
                        .HasForeignKey("PromotedRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaymentDetail");

                    b.Navigation("PromotedRequest");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Venue", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.Location", "Location")
                        .WithMany("Venues")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UserFollow", b =>
                {
                    b.HasOne("Event_Management_System.Models.Base.User", null)
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Event_Management_System.Models.Base.User", null)
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Event", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Enrollments");

                    b.Navigation("PromotedRequests");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Location", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PaymentDetail", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.PromotedRequest", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Enrollments");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("PaymentDetail");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Venue", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Event_Management_System.Models.Base.Organizer", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PromotedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
